/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LONG
 */
public final class OrderHistory extends javax.swing.JFrame {

    /**
     * Creates new form OrderH
     */
    
    int result;
    
    public OrderHistory() {
        initComponents();
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel5.setVisible(false);
        
        showup();

        
        final String[] cidList = getListFromSQL("customer","cid"); 
        final String[] eventList = getListFromSQL("manage_event_locate","event_name");
        
        cidBox.setModel(new javax.swing.DefaultComboBoxModel<>(cidList));
        eventBox.setModel(new javax.swing.DefaultComboBoxModel<>(eventList));
        //cidBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE CID"}));
        //eventBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE EVENT" }));
        
        //String OfficeNameList = getStringFromSQL("manage_event_locate","office_name",eventBox.getName());
    }
    
    public String[] getListFromSQL(String from, String what){
        
        System.out.println("line 51: entering getListFromSQL");//testing
        ArrayList<String> list = new ArrayList<String>();
        try{    
               
               connection c = connection.getInstance();
               Statement stmt = connection.conn.createStatement();
               
               ResultSet rs = stmt.executeQuery("SELECT "+ what +" FROM " + from);
               
        while (rs.next()){
                list.add(rs.getString(what));
            }
           }
           catch (Exception e){
           JOptionPane.showMessageDialog(this,e);
                   }
        
        String[] str = list.toArray(new String[list.size()]);
        System.out.println("line69: " + str.length);
        return str;
    }
    
    public String getStringFromSQL(String from, String what, String where){
//        String office = getStringFromSQL("manage_event_locate","office_name",event);


        String str= new String();
        try{    
               
               connection c = connection.getInstance();
               Statement stmt = connection.conn.createStatement();
               
               //System.out.println("SELECT "+what+" FROM "+from+" WHERE "+ "event_name="+ "\""+where+"\";");
              
               ResultSet rs;

               rs= stmt.executeQuery("SELECT "+what+" FROM "+from+" WHERE "+ "event_name="+ "\""+where+"\";");

               //ResultSet rs = stmt.executeQuery("SELECT office_name FROM manage_event_locate WHERE event_name=\"SAMSKARA - Immersive Art Experience\";");
//               
               rs.next();
               str=rs.getString(what);
//               System.out.println("hi666");
//               System.out.println("str!!: " +str);
        }
//        while (rs.next()){
//                str=rs.getString(what);
//            }
//           }
           catch (Exception e){
               System.out.println("line 89");
           JOptionPane.showMessageDialog(this,e);
                   }
        
        return str;
    }
    
    public void showup(){
    
        try{    
                
                
               connection c = connection.getInstance();
               Statement stmt = connection.conn.createStatement();
               
               ResultSet rs = stmt.executeQuery("SELECT * FROM buy_ticket_name");
               DefaultTableModel tm=(DefaultTableModel) table.getModel();
               tm.setRowCount(0);

               
        while (rs.next()){
            Object o[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
            
            tm.addRow(o);
    
            }
           }
           catch (Exception e){
           JOptionPane.showMessageDialog(this,e);
                   }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ShowButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cidBox = new javax.swing.JComboBox<>();
        eventBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer ID:");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ConfirmNUM", "CID", "Event Name", "Office Name"
            }
        ));
        jScrollPane1.setViewportView(table);

        ShowButton.setText("Refresh");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("doing order all his!");

        jLabel3.setText("doing searching!");

        jLabel4.setText("Qurry:");

        cidBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cidBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cidBoxMouseClicked(evt);
            }
        });

        eventBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        eventBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventBoxMouseClicked(evt);
            }
        });

        jButton1.setText("Buy Ticket");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cidBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ShowButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowButton)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        // TODO add your handling code here:
        
        try{    
                
                
               connection c = connection.getInstance();
               Statement stmt = connection.conn.createStatement();
               
               ResultSet rs = stmt.executeQuery("SELECT * FROM buy_ticket_name");
               DefaultTableModel tm=(DefaultTableModel) table.getModel();
               tm.setRowCount(0);

               
               jLabel2.setText("SELECT * FROM buy_ticket_name");
               jLabel2.setVisible(true);
               jLabel3.setVisible(false);
               jLabel5.setVisible(false);
               
        while (rs.next()){
            Object o[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
            
            tm.addRow(o);
    
            }
           }
           catch (Exception e){
           JOptionPane.showMessageDialog(this,e);
                   }
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String cid = jTextField1.getText();
        
        
        try{
            
                
               connection c = connection.getInstance();
               Statement stmt = connection.conn.createStatement();
               
               ResultSet rs = stmt.executeQuery("SELECT * FROM buy_ticket_name WHERE cid="+ cid);
               DefaultTableModel tm=(DefaultTableModel) table.getModel();
               tm.setRowCount(0);
               
               jLabel3.setText("SELECT * FROM buy_ticket_name WHERE cid="+ cid);
               jLabel2.setVisible(false);
               jLabel3.setVisible(true);
               jLabel5.setVisible(false);

        while (rs.next()){
            Object o[]={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
            //Object o[][] = customer.getAllCustomer();
            tm.addRow(o);
    
            }
           }
           catch (Exception e){
           JOptionPane.showMessageDialog(this,e);
                   }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void cidBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cidBoxMouseClicked
        // TODO add your handling code here:
        
        //cidBox.setModel(new javax.swing.DefaultComboBoxModel<>(cidList));
        //eventBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE EVENT" }));
        
    }//GEN-LAST:event_cidBoxMouseClicked

    private void eventBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventBoxMouseClicked
        // TODO add your handling code here:
        
        //cidBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE CID"}));
        //eventBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE EVENT" }));
    }//GEN-LAST:event_eventBoxMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //get 最大confirm numer 然后加一
        
        String cn = new String();
        String[] slist = getListFromSQL("buy_ticket_name", "confirm_number");

        int max=0;
        for(int i=0;i<slist.length;i++){
            int a = Integer.parseInt(slist[i]);
            if(a>max){
                max=a;
            }
        }
        result = max+1;//

        cn = Integer.toString(result);

        String cid = (String) cidBox.getSelectedItem();
        String event  = (String) eventBox.getSelectedItem();

        String office = getStringFromSQL("manage_event_locate","office_name",event);
        

        PreparedStatement ps;
        connection c = connection.getInstance();
        try{
            ps = c.conn.prepareStatement("INSERT INTO buy_ticket_name(confirm_number, cid, Event_name, office_name)"
                    +"VALUES(?,?,?,?)");

            
            JOptionPane.showMessageDialog(this,"Buy ticket successful！");
            
          
            
            ps.setString(1,cn);
            ps.setString(2,cid);
            ps.setString(3,event);
            ps.setString(4,office);
            
            jLabel5.setText("INSERT INTO buy_ticket_name("+ cn+","+ cid+","+event+","+office+")" );
               jLabel2.setVisible(false);
               jLabel3.setVisible(false);
               jLabel5.setVisible(true);
            
            ps.executeUpdate();
            c.conn.commit();
            ps.close();
           


        } catch (SQLException e){
            System.out.println("Invalid input:" + e.getMessage());
            try{
                c.conn.rollback();
            } catch (SQLException e1){
                System.out.println("Message: "+ e);
            }
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderHistory().setVisible(true);
                
                
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton ShowButton;
    private javax.swing.JComboBox<String> cidBox;
    private javax.swing.JComboBox<String> eventBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private String[] getListFromSQL() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
